extends Node

signal status_panel_updated(text: String)
signal combat_log_appended(text: String, type: String)
signal cell_clicked(grid_pos: Vector2i)
signal dj_mode_toggled(is_active: bool)
signal tile_revealed(center: Vector2i, radius: int)
signal dj_fog_cleared(cleared: bool)
signal dj_cell_painted(type: int, pos: Vector2i)
signal unit_moved(id: String, from: Vector2i, to: Vector2i)
signal unit_defeated(id: String, is_hero: bool, xp: int)
signal trap_triggered(hero_name: String, damage: int, pos: Vector2i)
signal floating_text_requested(text: String, color: Color, pos: Vector2i)
signal chest_opened(hero_name: String, item: Object, pos: Vector2i)
signal altar_interacted(text: String)
signal bookshelf_interacted(text: String)
signal random_event_triggered(title: String, desc: String)
signal combat_started()
signal initiative_rolled(order: Array)
signal turn_started(unit: Dictionary)
signal action_economy_updated(has_moved: bool, has_acted: bool, can_undo_move: bool)
signal turn_ended(unit: Dictionary)
signal status_removed(unit_id: String, type: int)
signal combat_ended(victory: bool)
signal unit_move_undone(id: String, from: Vector2i)
signal state_changed(old_state: int, new_state: int)
signal dice_roll_requested(dice_type: int, amount: int, bonus: int)
signal attack_resolved(attacker_name: String, target_name: String, roll: int, mod: int, total: int, ac: int, is_hit: bool, is_crit: bool, is_fumble: bool, damage: int)
signal health_updated(unit_id: String, hp: int, hp_max: int, delta: int)
signal resource_updated(unit_id: String, res: int, res_max: int, res_name: String)
signal status_effect_applied(target_id: String, effect: Dictionary)
signal status_applied(target_id: String, type: int, duration: int)
signal heal_resolved(healer_name: String, target_name: String, amount: int)
signal item_added_to_inventory(item: Dictionary)
signal item_used(item_id: String, user_id: String)
signal inventory_updated(items: Array)
signal dialogue_requested(lines: Array)
signal dialogue_finished()
signal turn_banner_announced(title: String, subtitle: String, is_hero: bool)
